import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    description: "Smartphone flagship terbaru dari Apple dengan chip A17 Pro dan kamera 48MP yang revolusioner.",
    price: 18999000,
    originalPrice: 19999000,
    discount: 5,
    image: "/ip15pro.jpeg",
    category: "Smartphone",
    rating: 4.8,
    reviews: 1250,
    inStock: true,
  },
  {
    id: "2",
    name: "MacBook Air M3",
    description: "Laptop ultra-tipis dengan performa luar biasa berkat chip M3 dan daya tahan baterai hingga 18 jam.",
    price: 16999000,
    image: "/macbookair.jpg",
    category: "Laptop",
    rating: 4.9,
    reviews: 890,
    inStock: true,
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    description: "Headphone wireless dengan noise cancelling terbaik di kelasnya dan kualitas audio premium.",
    price: 4999000,
    originalPrice: 5499000,
    discount: 9,
    image: "/placeholder.svg?height=400&width=400",
    category: "Audio",
    rating: 4.7,
    reviews: 2100,
    inStock: true,
  },
  {
    id: "4",
    name: "Apple Watch Series 9",
    description: "Smartwatch canggih dengan fitur kesehatan lengkap dan performa yang lebih cepat.",
    price: 5999000,
    image: "/placeholder.svg?height=400&width=400",
    category: "Smartwatch",
    rating: 4.6,
    reviews: 750,
    inStock: true,
  },
  {
    id: "5",
    name: "Samsung Galaxy S24 Ultra",
    description: "Smartphone Android flagship dengan S Pen dan kamera 200MP untuk fotografi profesional.",
    price: 17999000,
    originalPrice: 18999000,
    discount: 5,
    image: "/placeholder.svg?height=400&width=400",
    category: "Smartphone",
    rating: 4.8,
    reviews: 980,
    inStock: true,
  },
  {
    id: "6",
    name: "Dell XPS 13",
    description: "Laptop premium dengan layar InfinityEdge dan performa tinggi untuk produktivitas maksimal.",
    price: 14999000,
    image: "/placeholder.svg?height=400&width=400",
    category: "Laptop",
    rating: 4.5,
    reviews: 650,
    inStock: true,
  },
  {
    id: "7",
    name: "AirPods Pro 2",
    description: "Earbuds wireless dengan adaptive transparency dan spatial audio untuk pengalaman mendengar terbaik.",
    price: 3499000,
    originalPrice: 3799000,
    discount: 8,
    image: "/placeholder.svg?height=400&width=400",
    category: "Audio",
    rating: 4.7,
    reviews: 1800,
    inStock: true,
  },
  {
    id: "8",
    name: "PlayStation 5",
    description: "Konsol gaming next-gen dengan grafis 4K dan loading super cepat menggunakan SSD.",
    price: 7999000,
    image: "/placeholder.svg?height=400&width=400",
    category: "Gaming",
    rating: 4.9,
    reviews: 3200,
    inStock: true,
  },
  {
    id: "9",
    name: "Canon EOS R6 Mark II",
    description: "Kamera mirrorless profesional dengan sensor full-frame dan video 4K untuk kreator konten.",
    price: 32999000,
    originalPrice: 34999000,
    discount: 6,
    image: "/placeholder.svg?height=400&width=400",
    category: "Kamera",
    rating: 4.8,
    reviews: 420,
    inStock: true,
  },
  {
    id: "10",
    name: 'iPad Pro 12.9"',
    description: "Tablet premium dengan chip M2 dan layar Liquid Retina XDR untuk produktivitas dan kreativitas.",
    price: 15999000,
    image: "/placeholder.svg?height=400&width=400",
    category: "Tablet",
    rating: 4.7,
    reviews: 890,
    inStock: true,
  },
]
